---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-deployment
  labels:
    name: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: addressbook
  template:
    metadata:
      labels:
        name: addressbook
    spec:
      containers:
      - name: addressbook
        image: anandr177/addressbook:v1.22
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
  labels:
    name: addressbook-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30010
  selector:
    name: addressbook
